[package]
name = "Morast"
version = "0.1.1"
edition = "2021"

[dependencies]
bevy = "0.17.3"
derive_more = "2.1.0"
log = "0.4.25"
rand = "0.9.2"
tokio = {version = "1.48.0", features = ["sync"]}

[build-dependencies]
bindgen = "0.72.0"
cc = "1.2.9"
